"""add bot_id in ride

Revision ID: 5e8c122fc567
Revises: 69aef5ae5028
Create Date: 2023-07-07 00:18:58.567688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8c122fc567'
down_revision = '69aef5ae5028'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('bot_id', sa.BigInteger(), nullable=True))
    op.create_unique_constraint(None, 'rides', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rides', type_='unique')
    op.drop_column('rides', 'bot_id')
    # ### end Alembic commands ###
