"""add rides taBLE

Revision ID: 69aef5ae5028
Revises: 97ee3c0272f7
Create Date: 2023-06-26 21:15:47.677289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69aef5ae5028'
down_revision = '97ee3c0272f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('payment_field', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'cards', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_table('rides')
    # ### end Alembic commands ###
