"""first

Revision ID: 97ee3c0272f7
Revises: 
Create Date: 2023-06-26 21:14:04.605797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ee3c0272f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accounts',
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('coupon', sa.String(), nullable=False),
    sa.Column('special_field', sa.JSON(), nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coupon'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cards',
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('upd_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('cvc', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
